# Generated by Django 3.1.13 on 2021-11-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='owner',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
