# Generated by Django 3.1.13 on 2021-11-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme', '0002_quiz_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='favorite_day',
            field=models.CharField(blank=True, choices=[('monday', 'monday'), ('tuesday', 'tuesday'), ('wednesday', 'wednesday'), ('thursday', 'thursday'), ('friday', 'friday'), ('saturday', 'saturday'), ('sunday', 'sunday')], default='friday', max_length=25, null=True),
        ),
    ]
