# Generated by Django 3.1.13 on 2021-11-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetme', '0004_auto_20211128_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
